# Puxa uma imagem com python
FROM python:3.12-slim-bullseye

LABEL maintainer="Thiago Silva"
LABEL email="thyagosousasilva@gmail.com"

RUN apt-get update && \
    apt-get install -y git curl lsof iputils-ping htop telnet && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

CMD [ "tail", "-f", "/dev/null" ]